### ISSUE TITLE
Not working?

### ISSUE THREAD

**Issue by theschweatyboy** [myuseringithub/syncActionEventAcrossBrowsingContext#1]
I got the script and enabled it, but nothing happens. I couldn't figure out how to install the script so I copied and pasted the code into an empty script. Could that be why?

**Comment by myuseringithub** [comment]
You will need to install it through [TemperMonkey](https://chrome.google.com/webstore/detail/tampermonkey/dhdgffkkebhmkfjojejmpbldmpobfkfo?hl=en) browser plugin. 

- Add new script to the plugin (copy the contents from the source code.
- Open several windows of the browser on the target website.
- Open browser console (F12) to verify that the events are being propagated when turned on. 
- Turn on the event propagation using the bound keys ("0" on each browser) - [Check comments for options](https://github.com/myuseringithub/syncActionEventAcrossBrowsingContext/blob/master/entrypoint.js#L193). 
- When you move the mouse in one browser or initiate keyboard events, it should be duplicated on the other browsers. You could try resizing the browsers so they have the same size and work as expected.

**Comment by safizn** [comment]
[Check documentation](https://github.com/myuseringithub/syncActionEventAcrossBrowsingContext/blob/master/README.md)
